default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hod-back-develop
  username: <YOUR_POSTGRESQL_USER_NAME>

test:
  <<: *default
  database: hod-back-test
  username: <YOUR_POSTGRESQL_USER_NAME>

production:
  <<: *default
  database: hod-back_production
  username: deploy